name: Python CI/CD

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Job 1: Running tests
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job
    steps:
    - name: Checkout code  # Step 1: Checkout the code from the repository
      uses: actions/checkout@v2

    - name: Set up Python  # Step 2: Set up Python version 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies  # Step 3: Install the necessary dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Run tests  # Step 4: Run your tests using Pytest
      run: pytest

